### PR TITLE
Add links to contacts again

### PR DESCRIPTION
**Pull request by LinqLover**
Originally implemented via #124, then accidentally removed via #117, here it is again 😅

Tiny PR, let's merge this one faaast.

### CODE REVIEW

**Review by felixauringer — APPROVED** [review]

**Comment by frcroth** [comment]
This merge broke the CI for some reason

**Comment by LinqLover** [comment]
Interesting, the same build has passed before pressing the merge button: https://github.com/hpi-swt2/connections-portal/actions/runs/504326073

**Comment by LinqLover** [comment]
Even more interesting, 348ebc7383a29e2c4404b7760694a7a67864bb24 has fixed it again and after retrying https://github.com/hpi-swt2/connections-portal/actions/runs/504692213 it was green again, too. We appear to have at least one flaky test ... ❄️

**Comment by felixauringer** [comment]
The reason for that is rather simple: Almost all of the user's attributes are generated randomly. The `user_search_spec.rb` (in `features`) searches for a part of the username and expects no or exactly one hit. If there is another name which also happens to contain the part that is searched for, there are more hits than the test expected. I already mentioned this in the [PR](https://github.com/hpi-swt2/connections-portal/pull/100#discussion_r559185070) but did not think that it will happen so quickly :sweat_smile:  I will write a fix for that.

**Comment by felixauringer** [comment]
The reason for that is rather simple: Almost all of the user's attributes are generated randomly. The `user_search_spec.rb` (in `features`) searches for a part of the username and expects no or exactly one hit. If there is another name which also happens to contain the part that is searched for, there are more hits than the test expected. I already mentioned this in the [PR](https://github.com/hpi-swt2/connections-portal/pull/100#discussion_r559185070) but did not think that it will happen so quickly :sweat_smile:  I will write a fix for that.

**Pull request merged**
